/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iqiyi_security_emulator_Utils */

#ifndef _Included_com_lyf_jason__detector_EmulatorDetector
#define _Included_com_lyf_jason_detector_EmulatorDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lyf_jason_EmulatorDetector
 * Method:    cacheExecute
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lyf_jason_detector_EmulatorDetector_cacheExecute
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
